export const beaconClerkAppearance = {
  variables: {
    colorBackground: '#141414',
    colorNeutral: '#404040',
    colorInputBackground: '#0f0f0f',
    colorInputText: '#e5e5e5',
    colorText: '#e5e5e5',
    colorTextSecondary: '#a3a3a3',
    colorPrimary: '#f97316',
    colorDanger: '#ef4444',
    borderRadius: '0px',
    fontFamily: 'var(--font-space-grotesk), system-ui, sans-serif',
    fontFamilyButtons: 'var(--font-space-grotesk), system-ui, sans-serif',
  },
  elements: {
    rootBox: 'w-full',
    cardBox: 'w-full border border-[#303030] bg-[#141414]',
    card: 'bg-[#141414] border border-[#404040] shadow-none rounded-none',
    headerTitle: 'text-[#fafafa] font-semibold tracking-tight text-[1.75rem]',
    headerSubtitle: 'text-[#b3b3b3] text-[0.95rem]',
    socialButtonsBlockButton:
      'border border-[#404040] bg-[#0f0f0f] hover:bg-[#1a1a1a] text-[#f5f5f5] rounded-none shadow-none',
    socialButtonsBlockButtonText: 'text-[#f5f5f5] font-medium',
    dividerLine: 'bg-[#404040]',
    dividerText: 'text-[#b3b3b3]',
    formFieldLabel: 'text-[#d4d4d4] uppercase tracking-[0.18em] text-[11px] font-medium',
    formFieldInput:
      'bg-[#0f0f0f] border border-[#4a4a4a] text-[#f5f5f5] placeholder:text-[#8a8a8a] rounded-none focus:border-[#f97316] focus:ring-0',
    formFieldInputShowPasswordButton: 'text-[#b3b3b3] hover:text-[#f5f5f5]',
    formButtonPrimary:
      'bg-[#f97316] hover:bg-[#ea580c] text-white font-semibold rounded-none shadow-none',
    footerActionLink: 'text-[#f97316] hover:text-[#fb923c]',
    footerActionText: 'text-[#b3b3b3]',
    formFieldSuccessText: 'text-[#f5f5f5]',
    formFieldWarningText: 'text-[#f5f5f5]',
    formFieldErrorText: 'text-[#fecaca]',
    identityPreviewText: 'text-[#f5f5f5]',
    identityPreviewEditButton: 'text-[#f97316] hover:text-[#fb923c]',
    otpCodeFieldInput:
      'bg-[#0f0f0f] border border-[#4a4a4a] text-[#f5f5f5] rounded-none focus:border-[#f97316]',
    alert: 'rounded-none border-[#4a4a4a] bg-[#161616]',
    alertText: 'text-[#f5f5f5]',
    formResendCodeLink: 'text-[#f97316] hover:text-[#fb923c]',
    footer: 'bg-transparent',
    navbar: 'bg-[#141414] border-r border-[#404040]',
    navbarButton: 'text-[#b3b3b3] hover:text-[#f5f5f5] hover:bg-[#1a1a1a] rounded-none',
    pageScrollBox: 'bg-[#141414]',
    profileSectionPrimaryButton:
      'bg-[#f97316] hover:bg-[#ea580c] text-white rounded-none shadow-none',
    profileSectionTitleText: 'text-[#f5f5f5]',
    profileSectionContent: 'border-[#404040]',
    badge: 'rounded-none',
  },
}
